# Generated by Django 2.0.4 on 2018-05-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='stockdata',
        ),
    ]
